[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "suprtools"
version = "2025.8.14"
dependencies = [
  "numpy",
  "matplotlib",
  "seaborn",
  "scipy",
  "lmfit",
  "openfermion",
  "tqdm",
  "scikit-image",
  "scikit-rf",
]
